services:
  db:
    container_name: postgres
    image: postgres:14.1
    environment:
      POSTGRES_USER: awss3
      POSTGRES_PASSWORD: awss3
      PGDATA: /data/postgres
    volumes:
      - db:/data/postgres
    ports:
      - "5332:5432"
    networks:
      - db
    restart: unless-stopped

  fs-sid-aws-api:
    container_name: fs-sid-aws-api
    image: kraken2091/fs-sid-aws-api
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/customer
    ports:
      - "8088:8080"
    networks:
      - db
    depends_on:
      - db
    restart: unless-stopped
  fs-sid-aws-react:
    container_name: fs-sid-aws-api-react
    image: kraken2091/fs-sid-aws-api-react
    build:
      context: frontend/react
      args:
        api_base_url: http://localhost:8088
    ports:
      - "3000:5173"
    depends_on:
      - fs-sid-aws-api
    restart: unless-stopped

networks:
  db:
    driver: bridge

volumes:
  db:
